# Generated by Django 4.0.2 on 2022-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manage', '0002_admin_alter_department_title_alter_userinfo_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='用户名')),
                ('admin', models.CharField(max_length=16, verbose_name='账号')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
    ]
